"""Stub file for custom_components/reflex_xtermjs/xtermjs.py"""

# ------------------- DO NOT EDIT ----------------------
# This file was generated by `reflex/utils/pyi_generator.py`!
# ------------------------------------------------------
from collections.abc import Mapping, Sequence
from typing import Any, Literal, TypeAlias

import reflex as rx
from reflex.components.component import NoSSRComponent
from reflex_base.event import (
    EventType,
    PointerEventInfo,
)
from reflex_base.vars.base import Var
from reflex_components_core.core.breakpoints import Breakpoints

from .props import (
    ImageOptions,
    LigatureOptions,
    OverviewRulerOptions,
    SearchOptions,
    WindowsPty,
    XTermTheme,
)

__all__ = ["ADDONS", "XTerm", "xterm"]
ADDONS = (
    "fit",
    "search",
    "web-links",
    "serialize",
    "clipboard",
    "unicode11",
    "unicode-graphemes",
    "image",
    "ligatures",
    "progress",
)
AddonName: TypeAlias = Literal[
    "fit",
    "search",
    "web-links",
    "serialize",
    "clipboard",
    "unicode11",
    "unicode-graphemes",
    "image",
    "ligatures",
    "progress",
]
CursorStyle: TypeAlias = Literal["block", "underline", "bar"]
CursorInactiveStyle: TypeAlias = Literal["outline", "block", "bar", "underline", "none"]
LogLevel: TypeAlias = Literal["trace", "debug", "info", "warn", "error", "off"]
Renderer: TypeAlias = Literal["dom", "webgl", "canvas"]
FontWeight: TypeAlias = Literal[
    "normal", "bold", "100", "200", "300", "400", "500", "600", "700", "800", "900"
]
_wrapper = rx.asset("xterm_wrapper.jsx", shared=True)

class XTerm(NoSSRComponent):
    @classmethod
    def create(
        cls,
        *children,
        terminal_id: Var[str] | str | None = None,
        cols: Var[int] | int | None = None,
        rows: Var[int] | int | None = None,
        auto_fit: Var[bool] | bool | None = None,
        fit_debounce_ms: Var[int] | int | None = None,
        width: Var[str] | str | None = None,
        height: Var[str] | str | None = None,
        addons: Var[
            list[
                Literal[
                    "clipboard",
                    "fit",
                    "image",
                    "ligatures",
                    "progress",
                    "search",
                    "serialize",
                    "unicode-graphemes",
                    "unicode11",
                    "web-links",
                ]
            ]
        ]
        | list[
            Literal[
                "clipboard",
                "fit",
                "image",
                "ligatures",
                "progress",
                "search",
                "serialize",
                "unicode-graphemes",
                "unicode11",
                "web-links",
            ]
        ]
        | None = None,
        renderer: Literal["canvas", "dom", "webgl"]
        | Var[Literal["canvas", "dom", "webgl"]]
        | None = None,
        unicode_version: Var[str] | str | None = None,
        websocket_url: Var[str] | str | None = None,
        attach_bidirectional: Var[bool] | bool | None = None,
        reconnect: Var[bool] | bool | None = None,
        reconnect_delay_ms: Var[int] | int | None = None,
        send_resize_on_socket: Var[bool] | bool | None = None,
        initial_text: Var[str] | str | None = None,
        read_only: Var[bool] | bool | None = None,
        allow_proposed_api: Var[bool] | bool | None = None,
        allow_transparency: Var[bool] | bool | None = None,
        alt_click_moves_cursor: Var[bool] | bool | None = None,
        convert_eol: Var[bool] | bool | None = None,
        cursor_blink: Var[bool] | bool | None = None,
        cursor_style: Literal["bar", "block", "underline"]
        | Var[Literal["bar", "block", "underline"]]
        | None = None,
        cursor_inactive_style: Literal["bar", "block", "none", "outline", "underline"]
        | Var[Literal["bar", "block", "none", "outline", "underline"]]
        | None = None,
        cursor_width: Var[int] | int | None = None,
        custom_glyphs: Var[bool] | bool | None = None,
        disable_stdin: Var[bool] | bool | None = None,
        draw_bold_text_in_bright_colors: Var[bool] | bool | None = None,
        fast_scroll_modifier: Literal["alt", "ctrl", "none", "shift"]
        | Var[Literal["alt", "ctrl", "none", "shift"]]
        | None = None,
        fast_scroll_sensitivity: Var[int] | int | None = None,
        font_family: Var[str] | str | None = None,
        font_size: Var[int] | int | None = None,
        font_weight: Literal[
            "100", "200", "300", "400", "500", "600", "700", "800", "900", "bold", "normal"
        ]
        | Var[
            Literal["100", "200", "300", "400", "500", "600", "700", "800", "900", "bold", "normal"]
        ]
        | None = None,
        font_weight_bold: Literal[
            "100", "200", "300", "400", "500", "600", "700", "800", "900", "bold", "normal"
        ]
        | Var[
            Literal["100", "200", "300", "400", "500", "600", "700", "800", "900", "bold", "normal"]
        ]
        | None = None,
        ignore_bracketed_paste_mode: Var[bool] | bool | None = None,
        letter_spacing: Var[float] | float | None = None,
        line_height: Var[float] | float | None = None,
        log_level: Literal["debug", "error", "info", "off", "trace", "warn"]
        | Var[Literal["debug", "error", "info", "off", "trace", "warn"]]
        | None = None,
        mac_option_click_forces_selection: Var[bool] | bool | None = None,
        mac_option_is_meta: Var[bool] | bool | None = None,
        minimum_contrast_ratio: Var[float] | float | None = None,
        overview_ruler: OverviewRulerOptions
        | Var[OverviewRulerOptions | dict[str, Any]]
        | dict[str, Any]
        | None = None,
        reflow_cursor_line: Var[bool] | bool | None = None,
        rescale_overlapping_glyphs: Var[bool] | bool | None = None,
        right_click_selects_word: Var[bool] | bool | None = None,
        screen_reader_mode: Var[bool] | bool | None = None,
        scroll_on_erase_in_display: Var[bool] | bool | None = None,
        scroll_on_user_input: Var[bool] | bool | None = None,
        scroll_sensitivity: Var[int] | int | None = None,
        scrollback: Var[int] | int | None = None,
        smooth_scroll_duration: Var[int] | int | None = None,
        tab_stop_width: Var[int] | int | None = None,
        theme: Var[XTermTheme | dict[str, Any]] | XTermTheme | dict[str, Any] | None = None,
        window_options: Var[dict[str, bool]] | dict[str, bool] | None = None,
        windows_pty: Var[WindowsPty | dict[str, Any]] | WindowsPty | dict[str, Any] | None = None,
        word_separator: Var[str] | str | None = None,
        search_options: SearchOptions
        | Var[SearchOptions | dict[str, Any]]
        | dict[str, Any]
        | None = None,
        image_options: ImageOptions
        | Var[ImageOptions | dict[str, Any]]
        | dict[str, Any]
        | None = None,
        ligature_options: LigatureOptions
        | Var[LigatureOptions | dict[str, Any]]
        | dict[str, Any]
        | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_bell: EventType[()] | None = None,
        on_binary: EventType[Any] | None = None,
        on_blur: EventType[()] | None = None,
        on_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_context_loss: EventType[()] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_cursor_move: EventType[()] | None = None,
        on_data: EventType[Any] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_focus: EventType[()] | None = None,
        on_key: EventType[Any] | None = None,
        on_line_feed: EventType[()] | None = None,
        on_link_click: EventType[Any] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_progress: EventType[Any] | None = None,
        on_ready: EventType[Any] | None = None,
        on_render: EventType[Any] | None = None,
        on_resize: EventType[Any] | None = None,
        on_scroll: EventType[Any] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_search_results: EventType[Any] | None = None,
        on_selection_change: EventType[Any] | None = None,
        on_socket_close: EventType[Any] | None = None,
        on_socket_error: EventType[Any] | None = None,
        on_socket_open: EventType[Any] | None = None,
        on_title_change: EventType[Any] | None = None,
        on_unmount: EventType[()] | None = None,
        on_write_parsed: EventType[()] | None = None,
        **props,
    ) -> XTerm:
        """Create a terminal, validating the requested addons.

        Args:
            *children: Ignored; the terminal renders its own container.
            terminal_id: Key used by the imperative API to reach this terminal. Must be unique within a page.
            cols: Initial column count. Ignored once ``auto_fit`` takes over.
            rows: Initial row count. Ignored once ``auto_fit`` takes over.
            auto_fit: Resize the terminal to its container using the fit addon.
            fit_debounce_ms: Debounce applied to container resize events, in milliseconds.
            width: CSS width of the terminal container.
            height: CSS height of the terminal container.
            addons: Addons to load. See :data:`ADDONS`.
            renderer: Renderer backend. ``canvas`` additionally requires ``@xterm/addon-canvas`` to be installed by the app; it falls back to ``dom`` when the package is missing.
            unicode_version: Unicode version activated by the unicode addons.
            websocket_url: WebSocket endpoint to attach the terminal to. A path such as ``/pty`` is resolved against the current origin.
            attach_bidirectional: Forward terminal input to the socket as well as socket output to the terminal.
            reconnect: Reopen the socket automatically after it closes.
            reconnect_delay_ms: Delay before a reconnection attempt, in milliseconds.
            send_resize_on_socket: Send ``{"type": "resize", "cols": .., "rows": ..}`` over the socket whenever the terminal is resized.
            initial_text: Text (ANSI escapes allowed) written once when the terminal mounts.
            read_only: Convenience flag that sets ``disable_stdin``.
            allow_proposed_api: Allow addons to use the proposed (unstable) API surface.
            allow_transparency: Let the background show through the terminal.
            alt_click_moves_cursor: Alt+click moves the prompt cursor to the click position.
            convert_eol: Translate lone ``\\n`` into ``\\r\\n``.
            cursor_blink: Blink the cursor.
            cursor_style: Cursor shape while focused.
            cursor_inactive_style: Cursor shape while unfocused.
            cursor_width: Cursor width in pixels when ``cursor_style`` is ``bar``.
            custom_glyphs: Draw box-drawing and block characters with custom glyphs.
            disable_stdin: Ignore keyboard input.
            draw_bold_text_in_bright_colors: Render bold text using the bright ANSI palette.
            fast_scroll_modifier: Modifier key that triggers fast scrolling.
            fast_scroll_sensitivity: Scroll multiplier while the fast-scroll modifier is held.
            font_family: Font stack. Prefer a monospaced family.
            font_size: Font size in pixels.
            font_weight: Weight used for normal text.
            font_weight_bold: Weight used for bold text.
            ignore_bracketed_paste_mode: Ignore bracketed paste mode.
            letter_spacing: Extra horizontal spacing between characters, in pixels.
            line_height: Line height as a multiplier of the font size.
            log_level: Console verbosity of xterm.js itself.
            mac_option_click_forces_selection: On macOS, Option+click forces a selection.
            mac_option_is_meta: On macOS, treat the Option key as Meta.
            minimum_contrast_ratio: Minimum contrast ratio enforced between foreground and background.
            overview_ruler: Geometry of the decoration overview ruler.
            reflow_cursor_line: Reflow the cursor line when the terminal is resized.
            rescale_overlapping_glyphs: Rescale glyphs that overflow their cell.
            right_click_selects_word: Right click selects the word under the pointer.
            screen_reader_mode: Optimize the DOM for screen readers.
            scroll_on_erase_in_display: Scroll to the bottom on an erase-in-display sequence.
            scroll_on_user_input: Scroll to the bottom whenever the user types.
            scroll_sensitivity: Number of lines scrolled per wheel notch.
            scrollback: Number of lines kept in the scrollback buffer.
            smooth_scroll_duration: Duration of smooth scrolling animations, in milliseconds.
            tab_stop_width: Width of a tab stop, in columns.
            theme: Colour theme.
            window_options: Which DEC window operations the terminal honours.
            windows_pty: Description of the Windows pty feeding this terminal.
            word_separator: Characters treated as word boundaries for double-click selection.
            search_options: Defaults merged into every search performed through the API.
            image_options: Options for the image addon.
            ligature_options: Options for the ligatures addon.
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the viewport scrolls, with the new scroll position.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_data: Fired for every piece of user input (keystrokes, paste, mouse codes).
            on_binary: Fired for binary (non-UTF8) input.
            on_key: Fired on each keypress with the produced sequence and a plain description of the keyboard event.
            on_title_change: Fired when the program running in the terminal changes the title.
            on_resize: Fired whenever the terminal geometry changes.
            on_bell: Fired on the bell character.
            on_line_feed: Fired on each line feed.
            on_cursor_move: Fired when the cursor moves.
            on_selection_change: Fired when the selection changes, with the selected text.
            on_render: Fired after a render pass, with the affected row range.
            on_write_parsed: Fired once a `write` call has been fully parsed.
            on_ready: Fired once the terminal is attached to the DOM and sized.
            on_search_results: Fired by the search addon with the active index and the match count.
            on_progress: Fired by the progress addon (ConEmu OSC 9;4) with state and value.
            on_context_loss: Fired when the WebGL context is lost and the renderer falls back.
            on_link_click: Fired when a link detected by the web-links addon is clicked.
            on_socket_open: Fired when the attached WebSocket opens, with the resolved URL.
            on_socket_close: Fired when the attached WebSocket closes, with close code and reason.
            on_socket_error: Fired when the attached WebSocket errors.
            **props: Component props.

        Returns:
            The terminal component.

        Raises:
            ValueError: If ``addons`` contains an unknown addon name.
        """

xterm = XTerm.create
